### PR TITLE
Issue9: update signal words

### PR DESCRIPTION
**Pull request by larsvilhuber**
Addresses #9, by expanding signal words.

Suggested by @sergiocorreia

### CODE REVIEW

**Comment by larsvilhuber** [comment]
@sergiocorreia can you test on your end?

**Comment by larsvilhuber** [comment]
Hm. **This may not be working**. Limitations of `txttool` maybe? May need post-processing instead.

**Comment by sergiocorreia** [comment]
Hi Lars,

Sorry for the long delay; I'm only now caching up on emails from last week. Let me review the recent changes/issues and maybe we can touch base next week? I had a few ideas for replacing txttool that could make the package much simpler.

**Comment by larsvilhuber** [comment]
Hey Sergio,

why don't I focus on fixing V1 first, getting it out (I know the solution to this problem). Then we can later publish a V2.

I would much rather we focus now on getting the conference for revamp of SSC organized. Stata might be onboard, as I mentioned. And I'm seeing more and more non-SSC packages on github or private web pages - it has be more streamlined. Un-Kit-ing SSC is a priority...

I have a few hard deadlines this week, next, but normally Thanksgiving is super productive for me (b/c not in the US...), so hopefully, I'll make that all work.

Lars


--
Lars Vilhuber, Economist
Cornell University
p: +1.607-330-5743
https://calendly.com/larsvilhuber
My working day may not be your working day. Please respond during your working day.
________________________________

**Pull request merged**
